apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: docker.io/rajsomesetty/dev-petclinic-apple:9-dev
          ports:
            - containerPort: 80
